# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-aio
    pullPolicy: IfNotPresent
    tag: v2.6.2

webui:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-webui
    pullPolicy: IfNotPresent
    tag: "v2.6.2"

testNode:
  multusIP: 172.16.100.2
  multusNetworkMask: 24
  image:
    repository: ubuntu #nicolaka/netshoot
    pullPolicy: IfNotPresent
    tag: jammy #v0.10

mongodb:
  image:
    repository: mongo
    pullPolicy: IfNotPresent
    tag: "6.0.1"

provisioning:    
  image:
    repository: free5gmano/nextepc-mongodb
    pullPolicy: IfNotPresent
    tag: "latest"

k8swait:
  repository: groundnuty/k8s-wait-for
  tag: v1.6
  pullPolicy: IfNotPresent  

ueransim:
   repository: registry.gitlab.com/infinitydon/registry/ueransim
   pullPolicy: IfNotPresent
   tag: "v3.2.6"

k8s:
  interface: eth0

amf:
  mcc: 208
  mnc: 93
  tac: 7
  sst: 1
  sd: 1
  networkName: Open5GS

ue1:
  imsi: "208930000000031"
  imei: "356938035643803"
  imeiSv: "4370816125816151"
  op: "63bfa50ee6523365ff14c1f45f88737d"
  secKey: "0C0A34601D4F07677303652C0462535B"
  multusIP: 192.168.20.100
  multusNetworkMask: 24  
  dnn: "internet"

ue2:
  imsi: "208930000000032"
  imei: "356938035643804"
  imeiSv: "4370816125816151"
  op: "63bfa50ee6523365ff14c1f45f88737d"
  secKey: "0C0A34601D4F07677303652C0462535B"
  multusIP: 192.168.21.100
  multusNetworkMask: 24
  dnn: "internet"  

gnb:
  amfPort: "38412"

prometheus:
  nodeExporter:
     repository: quay.io/prometheus/node-exporter
     tag: v1.3.1
     pullPolicy: IfNotPresent

upf:
  nodeName: "core5g-worker2"
  multusIP: 172.16.100.1
  multusNetworkMask: 24

