apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bsf-config
  labels:
    epc-mode: bsf
data:
  bsf.yaml: |
    logger:
        file: /var/log/open5gs/bsf.log

    bsf:
      sbi:
        - addr: 0.0.0.0
          advertise: {{ .Release.Name }}-bsf.{{ .Release.Namespace }}.svc.cluster.local
      discovery:
         delegated: no           
    sbi:
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true              
    scp:
     sbi:
       name: {{ .Release.Name }}-scp.{{ .Release.Namespace }}.svc.cluster.local
    nrf:
     sbi:
       name: {{ .Release.Name }}-nrf.{{ .Release.Namespace }}.svc.cluster.local 