apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-udr-config
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    logger:
        file: /var/log/open5gs/udr.log

    db_uri: mongodb://{{ .Release.Name }}-mongodb-svc/open5gs
    udr:
      sbi:
        - addr: 0.0.0.0
          advertise: {{ .Release.Name }}-udr.{{ .Release.Namespace }}.svc.cluster.local
      discovery:
         delegated: no           
    scp:
     sbi:
       name: {{ .Release.Name }}-scp.{{ .Release.Namespace }}.svc.cluster.local
    nrf:
     sbi:
       name: {{ .Release.Name }}-nrf.{{ .Release.Namespace }}.svc.cluster.local 
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true   